env:
  scenario: "cim"
  topology: "toy.4p_ssdd_l0.0"
  durations: 1120
main_loop:
  max_episode: 500
  early_stopping:
    warmup_ep: 50
    last_k: 10
    threshold: 0.05
state_shaping:
  look_back: 7
  max_ports_downstream: 2
  port_attributes:
    - "empty"
    - "full"
    - "on_shipper"
    - "on_consignee"
    - "booking"
    - "shortage"
    - "fulfillment"
  vessel_attributes:
    - "empty"
    - "full"
    - "remaining_space"
experience_shaping:
  time_window: 100
  fulfillment_factor: 1.0
  shortage_factor: 1.0
  time_decay_factor: 0.97
agents:
  algorithm:
    reward_decay: .0
    num_actions: 21
    policy_model:
      hidden_dims:
        - 256
        - 128
        - 64
      softmax_enabled: true
      batch_norm_enabled: false
    optimizer:
      lr: 0.001
  seed: 1024   # for reproducibility
distributed:
  group_name: "pg_distributed_test"
  actor:
    peer: {"actor": 1}
  learner:
    peer: {"actor_worker": 1}
  redis:
    host_name: "localhost"
    port: 6379
